### ISSUE TITLE
Review & update all photos on the website

### ISSUE THREAD

**Issue by iteles** [mosteirodelandim/landim-website#26]
Review all photos on the website for:
+ Relevance
+ Quality
+ Copyright infringements

## Sections
+ [x] Homepage
  + [x] Title image
  + [x] Tiles
+ [x] Início / Home 
+ [x] Quem Somos / About Us 
+ [x] Serviços / Services 
+ [x] Fotografias / Photo Gallery 
+ [x] História / History
+ [x] Jardins / Gardens 
+ [x] Vinho & Vinhas / Wine and Vineyards
+ [x] FAQs 
+ [x] Contactos / Contact Us 

## Tasks
+ [x] @iteles First-pass review of all photos and make suggestions for new ones
+ [x] @LuchoTurtle to review with Sofia
+ [x] @LuchoTurtle to make image changes required (convert to .webp for better performance)

**Comment by LuchoTurtle** [comment]
This issue and #30 are deployment blockers. We need to sort these two issues out before deploying ASAP. 
Also, issue #21 depends on this issue to be implemented.

**Comment by LuchoTurtle** [comment]
I've updated the website with all the necessary photos from Mosteiro's Photos account. All of them are properly SEO-friendly and have been reviewed for quality.

**Comment by iteles** [comment]
The truth is, once the site it up, we can easily change the photos! They can't be worse than the ones we have up already 😆 

It would be good to include the photographers in the `alt` text so there are no complaints.

**Comment by LuchoTurtle** [comment]
Agreed, although I don't know if we have such information on the photos used 🤔

**Comment by iteles** [comment]
All of the photos in the Landim photos drive are in albums, most of which include the info on photographers 👌🏻
