### ISSUE TITLE
Deploy to production domain

### ISSUE THREAD

**Issue by iteles** [mosteirodelandim/landim-website#27]
Currently the _new_ website is hosted at http://mosteirodelandim.surge.sh/

In order to deploy this to production, we need to complete the following tasks

## Tasks
+ [x] @iteles to speak to Mercatura (who currently hold domain name) and agree best course of action
+ [x] @iteles to email Mercatura and agree set up transfer of domain name to the Mosteiro
+ [x] @iteles to confirm what needs to be done to ensure domain continues to point to current/old site for now
+ [x] Domain name successfully transferred
+ [x] Ensure domain still points to current/old site
+ [x] Ensure all [critical issues](https://github.com/mosteirodelandim/landim-website/milestone/1) are complete
+ [x] Get the green light from the family 4
+ [x] Add Google Analytics tokens to new website so we don’t lose tracking (@LuchoTurtle, I have all the access we need for this)
+ [x] Follow the instructions [here](https://surge.sh/help/adding-a-custom-domain) to:
  + [x] Add a new `CNAME` to the domain in domain name provider
  + [x] Deploy the custom domain and save it using the `surge sh` CLI
+ [x] Confirm deployment was successful
+ [x] Confirm Google Analytics is still tracking correctly

**Comment by iteles** [comment]
Currently awaiting responses to enable transfer of domain name.

We need to be careful to set it up to currently point at the old site whilst we're completing the MVP milestone tasks ahead of deployment. Added tasks to OP.

**Comment by LuchoTurtle** [comment]
We're close to deploy this. I want to set up a pipeline and I'm keen on using Netlify. Apparently we already have the domain sorted (didn't Mercatura already sent you all the necessary info @iteles ?).

I just need the domain and the domain name servers and I can easily set this up with Netlify to have the site up and running.

**Comment by nelsonic** [comment]
FYI: this is what I see when I attempt to visit the site: https://www.mosteirodelandim.com/
<img width="923" alt="image" src="https://user-images.githubusercontent.com/194400/183344756-54d3e54b-f72a-4754-9792-21d0e05a3f2d.png">

**Comment by nelsonic** [comment]
If I click "Advanced" > Proceed ... then I see:

<img width="917" alt="image" src="https://user-images.githubusercontent.com/194400/183344920-92646ba5-0e6c-4ef1-8865-b66cf405dd3d.png">

This UX will be _killing_ the SEO & Conversion. 💀

**Comment by LuchoTurtle** [comment]
Closing this issue, as the site has been deployed.

https://mosteirodelandim.com/
