### ISSUE TITLE
Ensure continuity of Google Analytics data

### ISSUE THREAD

**Issue by iteles** [mosteirodelandim/landim-website#28]
Currently our analytics tokens are housed with/by the company that created the original site.

We need to ensure we don’t lose our historical data in the move to our own site.

## Tasks
+ [ ] @iteles Speak to Mercatura to confirm whether GA token can be transferred
+ [ ] @iteles Confirm GA token transfer
+ [ ] @LuchoTurtle Ensure new site has GA token before deployment

**Comment by LuchoTurtle** [comment]
@iteles please confirm if we're sticking with Google Analytics or doing some sort of self-hosting with [Plausible](https://plausible.io/docs/plausible-analytics-self-hosted-guides) or [Matomo](https://matomo.org/pricing/) 👌
