### ISSUE TITLE
Review & update all content on the website

### ISSUE THREAD

**Issue by LuchoTurtle** [mosteirodelandim/landim-website#30]
We ought to review the content for the whole website. Some pages are with _lorem impsum_ since there wasn't anything tangible that was agreed. This issue should require standup.

For each page, we got to review:
+ The content
+ Translation (i18n)
+ The layout (I've already created the pages with the layout that I think work but this has to be commonly agreed by all parties)

## Sections
+ [x] Homepage
+ [x] Início / Home 
+ [x] Quem Somos / About Us 
+ [x] Serviços / Services #15
+ [x] Fotografias / Photo Gallery 
+ [x] História / History
+ [x] Jardins / Gardens 
+ [x] Vinho & Vinhas / Wine and Vineyards
+ [x] FAQs 
+ [x] Contactos / Contact Us 

## Tasks
+ [x] @iteles We have to meet together and decide on text. This should require external dependencies with the rest of the family.
+ [x] Review with family.
+ [x] @LuchoTurtle will make any changes needed.

**Comment by iteles** [comment]
Did you actually update all this content? 😆

**Comment by LuchoTurtle** [comment]
I wrote everything that I thought would be relevant 😂 . But of course, it will be probably as feedback comes along
